
POST http://localhost:5000/recipes
Content-Type: application/json

{
    "title": "recipe 6",
    "img": "img",
    "ingredients": [ "ingredient 2", "ingredient 4" ],
    "category": "Con carne",
    "time":"20 minutos",
    "likes": 12,
    "steps": [ "step 1", "step 2" ],
    "timeFridge": "20 minutos",
    "timeFreezer": "20 minutos",
    "tags": [ "tag 3", "tag 2" ]
}

###

GET http://localhost:5000/recipes

###

GET http://localhost:5000/recipes/6138183a56a45cec0353bcc3

###

DELETE http://localhost:5000/recipes/6138183a56a45cec0353bcc3

###

PATCH http://localhost:5000/recipes/61381d6d900dc801dc660361
Content-Type: application/json

{
    "title": "recipe 3",
    "img": "img2",
    "ingredients": [ "ingredient 2", "ingredient 4" ],
    "category": "Con carne",
    "time":"15 minutos",
    "likes": 12,
    "steps": [ "step 1", "step 2" ],
    "timeFridge": "20 minutos",
    "timeFreezer": "20 minutos",
    "tags": [ "tag 1", "tag 2" ]
}

###

GET http://localhost:5000/recipes/search?search=tag+1&searh=tag+2&field=tags